# Generated by Django 5.2 on 2025-05-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadmap', '0002_assessmentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='full_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='milestone_12_months',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='milestone_3_months',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='milestone_6_months',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='milestone_9_months',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='milestone_start',
            field=models.TextField(blank=True, null=True),
        ),
    ]
